"""Single source of truth for user-actionable error codes (Plan 30 Task 2).

Every `HTTPException(detail=…)` site in `src/hermes/routes/*.py` emits one
of these `ErrorCode` values, either as a bare string (FastAPI serialises
to `{"detail": "<CODE>"}`) or wrapped in `{"code": "<CODE>", "params":
{...}}` when the human-readable form needs interpolation. The frontend
renders `errors.<CODE>` via i18n, so the backend stays locale-agnostic
and the FE owns translation. Diagnostics checks follow the same shape
(`code` + optional `params`) rather than a free-form `message`.

UPPER_SNAKE name == value (enforced by `tests/test_errors_enum.py`) — the
FE looks up `errors.${detail.code}`, so divergence between `.name` and
`.value` would silently break translation when an enum member is
renamed.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    # ── Generic request shape ────────────────────────────────────────
    # Catch-all for str(exc) pass-throughs (Pydantic / repository
    # ValueError). The raw English message lands in
    # `params.message` for debugging — FE renders the localised
    # template around it.
    INVALID_REQUEST = "INVALID_REQUEST"
    REQUEST_INVALID_JSON = "REQUEST_INVALID_JSON"
    REQUEST_INVALID_OFFSET = "REQUEST_INVALID_OFFSET"
    REQUEST_LIMIT_OUT_OF_RANGE = "REQUEST_LIMIT_OUT_OF_RANGE"
    REQUEST_INVALID_STATUS = "REQUEST_INVALID_STATUS"
    REQUEST_INVALID_PERIOD = "REQUEST_INVALID_PERIOD"
    REQUEST_INVALID_MIN_LEVEL = "REQUEST_INVALID_MIN_LEVEL"
    REQUEST_TAIL_OUT_OF_RANGE = "REQUEST_TAIL_OUT_OF_RANGE"

    # ── Chat / sessions ──────────────────────────────────────────────
    CHAT_INVALID_SESSION = "CHAT_INVALID_SESSION"
    CHAT_SESSION_NOT_FOUND = "CHAT_SESSION_NOT_FOUND"
    CHAT_UPSTREAM_TIMEOUT = "CHAT_UPSTREAM_TIMEOUT"
    CHAT_UPSTREAM_UNREACHABLE = "CHAT_UPSTREAM_UNREACHABLE"
    CHAT_UPSTREAM_NON_JSON = "CHAT_UPSTREAM_NON_JSON"
    CHAT_UPSTREAM_ERROR = "CHAT_UPSTREAM_ERROR"

    # ── Conversations / messages / attachments ──────────────────────
    CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"
    CONVERSATION_NOT_WEB = "CONVERSATION_NOT_WEB"
    CONVERSATION_TITLE_BLANK = "CONVERSATION_TITLE_BLANK"
    CONVERSATION_NO_USER_MESSAGE_TO_RETRY = "CONVERSATION_NO_USER_MESSAGE_TO_RETRY"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_ONLY_USER_EDITABLE = "MESSAGE_ONLY_USER_EDITABLE"
    ATTACHMENT_REQUIRES_CONVERSATION = "ATTACHMENT_REQUIRES_CONVERSATION"
    ATTACHMENT_UNKNOWN_IDS = "ATTACHMENT_UNKNOWN_IDS"
    ATTACHMENT_UNSUPPORTED_TYPE = "ATTACHMENT_UNSUPPORTED_TYPE"
    ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE"

    # ── Runs / approvals / tools ─────────────────────────────────────
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
    APPROVAL_ALREADY_RESOLVED = "APPROVAL_ALREADY_RESOLVED"
    TOOL_NOT_IN_ALWAYS_ALLOWED = "TOOL_NOT_IN_ALWAYS_ALLOWED"
    TOOL_NOT_IN_SESSION_ALLOWED = "TOOL_NOT_IN_SESSION_ALLOWED"

    # ── Notes ────────────────────────────────────────────────────────
    NOTE_NOT_FOUND = "NOTE_NOT_FOUND"

    # ── Tasks / scheduler ────────────────────────────────────────────
    TASK_NOT_FOUND = "TASK_NOT_FOUND"
    TASK_DUE_OR_SCHEDULE_REQUIRED = "TASK_DUE_OR_SCHEDULE_REQUIRED"
    TASK_UNKNOWN_TIMEZONE = "TASK_UNKNOWN_TIMEZONE"
    TASK_SCHEDULER_NOT_CONFIGURED = "TASK_SCHEDULER_NOT_CONFIGURED"

    # ── Sandbox ──────────────────────────────────────────────────────
    SANDBOX_NOT_CONFIGURED = "SANDBOX_NOT_CONFIGURED"

    # ── LLM credentials / OAuth / models ─────────────────────────────
    LLM_CREDENTIAL_NOT_FOUND = "LLM_CREDENTIAL_NOT_FOUND"
    LLM_CREDENTIAL_VANISHED = "LLM_CREDENTIAL_VANISHED"
    LLM_OAUTH_PENDING = "LLM_OAUTH_PENDING"
    LLM_OAUTH_NOT_AUTHORIZED = "LLM_OAUTH_NOT_AUTHORIZED"
    LLM_OAUTH_NOT_PENDING = "LLM_OAUTH_NOT_PENDING"
    LLM_OAUTH_FLOW_NOT_FOUND = "LLM_OAUTH_FLOW_NOT_FOUND"
    LLM_OAUTH_NO_CREDENTIALS = "LLM_OAUTH_NO_CREDENTIALS"
    LLM_OAUTH_START_FAILED = "LLM_OAUTH_START_FAILED"
    LLM_OAUTH_CODE_REJECTED = "LLM_OAUTH_CODE_REJECTED"
    LLM_PROVIDER_FAILED = "LLM_PROVIDER_FAILED"

    # ── MCP servers ──────────────────────────────────────────────────
    MCP_MANAGER_NOT_INITIALISED = "MCP_MANAGER_NOT_INITIALISED"
    MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND"
    MCP_SERVER_NAME_CONFLICT = "MCP_SERVER_NAME_CONFLICT"
    MCP_SERVER_INVALID_NAME = "MCP_SERVER_INVALID_NAME"
    MCP_HTTP_REQUIRES_URL = "MCP_HTTP_REQUIRES_URL"
    MCP_HTTP_FORBIDS_COMMAND = "MCP_HTTP_FORBIDS_COMMAND"
    MCP_HTTP_FORBIDS_ENV = "MCP_HTTP_FORBIDS_ENV"
    MCP_STDIO_REQUIRES_COMMAND = "MCP_STDIO_REQUIRES_COMMAND"
    MCP_STDIO_FORBIDS_URL = "MCP_STDIO_FORBIDS_URL"

    # ── Skills ───────────────────────────────────────────────────────
    SKILL_INVALID_SLUG = "SKILL_INVALID_SLUG"
    SKILL_SLUG_CONFLICT = "SKILL_SLUG_CONFLICT"
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"

    # ── Preferences / personas / channels ────────────────────────────
    PERSONA_NOT_FOUND = "PERSONA_NOT_FOUND"
    PERSONA_NAME_CONFLICT = "PERSONA_NAME_CONFLICT"
    PERSONA_DEFAULT_DEMOTE = "PERSONA_DEFAULT_DEMOTE"
    PERSONA_DEFAULT_DELETE = "PERSONA_DEFAULT_DELETE"
    PERSONA_REF_INVALID = "PERSONA_REF_INVALID"
    PERSONA_SKILL_ACTIVATION_INVALID = "PERSONA_SKILL_ACTIVATION_INVALID"
    PERSONA_FRAGMENTS_ALL_EMPTY = "PERSONA_FRAGMENTS_ALL_EMPTY"
    PERSONA_HISTORY_NOT_FOUND = "PERSONA_HISTORY_NOT_FOUND"
    PERSONA_HISTORY_PERSONA_MISMATCH = "PERSONA_HISTORY_PERSONA_MISMATCH"
    PERSONA_NO_CREDENTIAL = "PERSONA_NO_CREDENTIAL"
    PERSONA_INVALID_CREDENTIAL = "PERSONA_INVALID_CREDENTIAL"
    PERSONA_INVALID_MODEL = "PERSONA_INVALID_MODEL"
    CHANNEL_NOT_FOUND = "CHANNEL_NOT_FOUND"
    CHANNEL_ROW_MISSING = "CHANNEL_ROW_MISSING"

    # ── Workspaces (CRUD + on-disk + git) ────────────────────────────
    WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND"
    WORKSPACE_ROOT_NOT_FOUND = "WORKSPACE_ROOT_NOT_FOUND"
    WORKSPACE_ALREADY_EXISTS = "WORKSPACE_ALREADY_EXISTS"
    WORKSPACE_SANDBOX_NOT_RUNNING = "WORKSPACE_SANDBOX_NOT_RUNNING"
    WORKSPACE_INVALID_PATH = "WORKSPACE_INVALID_PATH"
    WORKSPACE_PATH_NOT_FOUND = "WORKSPACE_PATH_NOT_FOUND"
    WORKSPACE_PATH_EXISTS = "WORKSPACE_PATH_EXISTS"
    WORKSPACE_PATH_IS_DIRECTORY = "WORKSPACE_PATH_IS_DIRECTORY"
    WORKSPACE_PATH_IS_DIRECTORY_USE_TREE = "WORKSPACE_PATH_IS_DIRECTORY_USE_TREE"
    WORKSPACE_PATH_NOT_DIRECTORY = "WORKSPACE_PATH_NOT_DIRECTORY"
    WORKSPACE_PATH_NOT_REGULAR = "WORKSPACE_PATH_NOT_REGULAR"
    WORKSPACE_PATH_MUST_BE_FILE = "WORKSPACE_PATH_MUST_BE_FILE"
    WORKSPACE_PARENT_NOT_FOUND = "WORKSPACE_PARENT_NOT_FOUND"
    WORKSPACE_PARENT_NOT_DIRECTORY = "WORKSPACE_PARENT_NOT_DIRECTORY"
    WORKSPACE_FILE_NUL_BYTES = "WORKSPACE_FILE_NUL_BYTES"
    WORKSPACE_FILE_TOO_LARGE = "WORKSPACE_FILE_TOO_LARGE"
    WORKSPACE_FILE_SHA_MISMATCH = "WORKSPACE_FILE_SHA_MISMATCH"
    WORKSPACE_DELETE_NOT_REGULAR = "WORKSPACE_DELETE_NOT_REGULAR"
    WORKSPACE_DELETE_FAILED = "WORKSPACE_DELETE_FAILED"
    WORKSPACE_RENAME_SAME_PATH = "WORKSPACE_RENAME_SAME_PATH"
    WORKSPACE_RENAME_SRC_NOT_FOUND = "WORKSPACE_RENAME_SRC_NOT_FOUND"
    WORKSPACE_RENAME_SRC_NOT_REGULAR = "WORKSPACE_RENAME_SRC_NOT_REGULAR"
    WORKSPACE_RENAME_DEST_EXISTS = "WORKSPACE_RENAME_DEST_EXISTS"
    WORKSPACE_RENAME_FAILED = "WORKSPACE_RENAME_FAILED"
    WORKSPACE_LIST_FAILED = "WORKSPACE_LIST_FAILED"
    WORKSPACE_NOT_GIT_REPO = "WORKSPACE_NOT_GIT_REPO"
    WORKSPACE_GIT_DIRTY = "WORKSPACE_GIT_DIRTY"
    WORKSPACE_GIT_INVALID_BRANCH = "WORKSPACE_GIT_INVALID_BRANCH"
    WORKSPACE_GIT_INVALID_CURRENT_BRANCH = "WORKSPACE_GIT_INVALID_CURRENT_BRANCH"
    WORKSPACE_GIT_DESTRUCTIVE_DISABLED = "WORKSPACE_GIT_DESTRUCTIVE_DISABLED"
    WORKSPACE_GIT_PUSH_DETACHED_HEAD = "WORKSPACE_GIT_PUSH_DETACHED_HEAD"
    WORKSPACE_GIT_COMMAND_FAILED = "WORKSPACE_GIT_COMMAND_FAILED"

    # ── Logs ─────────────────────────────────────────────────────────
    LOGS_DISABLED = "LOGS_DISABLED"

    # ── Diagnostics (per-subsystem status codes) ─────────────────────
    DIAG_DB_NOT_INITIALISED = "DIAG_DB_NOT_INITIALISED"
    DIAG_DB_REACHABLE = "DIAG_DB_REACHABLE"
    DIAG_DB_UNREACHABLE = "DIAG_DB_UNREACHABLE"
    DIAG_LLM_NO_CREDENTIAL = "DIAG_LLM_NO_CREDENTIAL"
    DIAG_LLM_ACTIVE = "DIAG_LLM_ACTIVE"
    DIAG_LLM_NEEDS_DB = "DIAG_LLM_NEEDS_DB"
    DIAG_SCHEDULER_NOT_STARTED = "DIAG_SCHEDULER_NOT_STARTED"
    DIAG_SCHEDULER_LOOP_STOPPED = "DIAG_SCHEDULER_LOOP_STOPPED"
    DIAG_SCHEDULER_RUNNING = "DIAG_SCHEDULER_RUNNING"
    DIAG_WORKSPACE_NEEDS_DB = "DIAG_WORKSPACE_NEEDS_DB"
    DIAG_WORKSPACE_NONE = "DIAG_WORKSPACE_NONE"
    DIAG_WORKSPACE_CONFIGURED = "DIAG_WORKSPACE_CONFIGURED"
    DIAG_SANDBOX_CONFIGURED = "DIAG_SANDBOX_CONFIGURED"
    DIAG_SANDBOX_SOCKET_MISSING = "DIAG_SANDBOX_SOCKET_MISSING"
    DIAG_SANDBOX_MANAGER_FAILED = "DIAG_SANDBOX_MANAGER_FAILED"
